// Base de citations FILAX — finance, épargne, discipline.
// Règle: chaque citation tient sur UNE seule ligne courte (max 42 caractères).
export interface Quote {
  text: string;
  author: string;
}

export const QUOTES: Quote[] = [
  { text: "Achetez de la valeur, pas du prix.", author: "Charlie Munger" },
  { text: "La discipline protège le capital.", author: "Warren Buffett" },
  { text: "L'épargne crée des options.", author: "Anonyme" },
  { text: "La patience multiplie les rendements.", author: "Warren Buffett" },
  { text: "Le risque exige la connaissance.", author: "Peter Lynch" },
  { text: "Le capital suit la confiance.", author: "Anonyme" },
  { text: "La constance construit la richesse.", author: "Anonyme" },
  { text: "Les habitudes dirigent les résultats.", author: "James Clear" },
  { text: "Chaque dépense mérite une raison.", author: "Anonyme" },
  { text: "L'investissement récompense le temps.", author: "Warren Buffett" },
  { text: "L'intégrité protège les profits.", author: "Charlie Munger" },
  { text: "L'argent respecte la discipline.", author: "Anonyme" },
  { text: "Le savoir réduit le risque.", author: "Benjamin Franklin" },
  { text: "Le contrôle précède la croissance.", author: "Anonyme" },
  { text: "La prudence préserve la fortune.", author: "Benjamin Graham" },
  { text: "Les émotions coûtent cher.", author: "Warren Buffett" },
  { text: "La richesse aime la régularité.", author: "Anonyme" },
  { text: "Les décisions créent le patrimoine.", author: "Anonyme" },
  { text: "Le temps valorise les actifs.", author: "Warren Buffett" },
  { text: "L'ordre améliore les finances.", author: "Anonyme" },
  { text: "Le capital demande de la patience.", author: "Ray Dalio" },
  { text: "L'épargne prépare l'avenir.", author: "Anonyme" },
  { text: "La simplicité favorise les profits.", author: "Charlie Munger" },
  { text: "Le budget révèle les priorités.", author: "Anonyme" },
  { text: "Les objectifs orientent l'argent.", author: "Anonyme" },
  { text: "Le rendement suit la discipline.", author: "Anonyme" },
  { text: "L'attention protège les ressources.", author: "Anonyme" },
  { text: "La connaissance attire les opportunités.", author: "Peter Lynch" },
  { text: "Les chiffres racontent la vérité.", author: "Warren Buffett" },
  { text: "La maîtrise réduit les pertes.", author: "Anonyme" },
  { text: "L'action cohérente crée la richesse.", author: "Anonyme" },
  { text: "La vision guide le capital.", author: "Ray Dalio" },
  { text: "Les actifs financent la liberté.", author: "Robert Kiyosaki" },
  { text: "La prudence précède l'expansion.", author: "Benjamin Graham" },
  { text: "Le patrimoine récompense la constance.", author: "Anonyme" },
  { text: "Les bonnes habitudes enrichissent.", author: "James Clear" },
  { text: "La clarté améliore les décisions.", author: "Anonyme" },
  { text: "Le savoir accumule la valeur.", author: "Charlie Munger" },
  { text: "L'argent exige de la responsabilité.", author: "Anonyme" },
  { text: "Le progrès aime la discipline.", author: "Anonyme" },
  { text: "Les économies financent les projets.", author: "Anonyme" },
  { text: "Le capital grandit avec le temps.", author: "Warren Buffett" },
  { text: "Les résultats suivent les systèmes.", author: "James Clear" },
  { text: "La préparation réduit les erreurs.", author: "Anonyme" },
  { text: "Les profits suivent la valeur.", author: "Warren Buffett" },
  { text: "La patience protège l'investisseur.", author: "Benjamin Graham" },
  { text: "Le contrôle favorise l'abondance.", author: "Anonyme" },
  { text: "Les petites économies s'accumulent.", author: "Anonyme" },
  { text: "L'ordre crée l'efficacité.", author: "Anonyme" },
  { text: "Les actifs créent des revenus.", author: "Robert Kiyosaki" },
  { text: "La discipline renforce la liberté.", author: "Jocko Willink" },
  { text: "Les chiffres guident les décisions.", author: "Peter Drucker" },
  { text: "Le temps récompense les investisseurs.", author: "Warren Buffett" },
  { text: "L'effort cohérent produit la croissance.", author: "Anonyme" },
  { text: "La prudence protège l'avenir.", author: "Anonyme" },
  { text: "Le capital apprécie la patience.", author: "Anonyme" },
  { text: "Les choix déterminent la richesse.", author: "Anonyme" },
  { text: "La connaissance précède l'investissement.", author: "Peter Lynch" },
  { text: "Les habitudes façonnent le patrimoine.", author: "James Clear" },
  { text: "La simplicité réduit les erreurs.", author: "Charlie Munger" },
  { text: "Le budget protège les objectifs.", author: "Anonyme" },
  { text: "L'épargne réduit la dépendance.", author: "Anonyme" },
  { text: "Les actifs récompensent la vision.", author: "Robert Kiyosaki" },
  { text: "La cohérence produit les résultats.", author: "Anonyme" },
  { text: "L'argent suit la valeur créée.", author: "Warren Buffett" },
  { text: "Le savoir améliore les rendements.", author: "Peter Lynch" },
  { text: "Les ressources exigent de l'attention.", author: "Anonyme" },
  { text: "La patience évite les erreurs coûteuses.", author: "Benjamin Graham" },
  { text: "La responsabilité attire la confiance.", author: "Anonyme" },
  { text: "L'investissement exige de la discipline.", author: "Ray Dalio" },
  { text: "Les profits récompensent la valeur.", author: "Warren Buffett" },
  { text: "Le capital préfère la stabilité.", author: "Anonyme" },
  { text: "La vision favorise la croissance.", author: "Ray Dalio" },
  { text: "Les économies renforcent la sécurité.", author: "Anonyme" },
  { text: "La maîtrise protège les gains.", author: "Anonyme" },
  { text: "Les actifs travaillent sans repos.", author: "Robert Kiyosaki" },
  { text: "La préparation crée l'avantage.", author: "Anonyme" },
  { text: "Le temps amplifie les résultats.", author: "Warren Buffett" },
  { text: "La discipline accélère le progrès.", author: "Jocko Willink" },
  { text: "Les rendements récompensent la patience.", author: "Benjamin Graham" },
  { text: "La valeur attire le capital.", author: "Warren Buffett" },
  { text: "Les systèmes battent les impulsions.", author: "James Clear" },
  { text: "Le contrôle réduit les risques.", author: "Ray Dalio" },
  { text: "L'épargne renforce l'indépendance.", author: "Anonyme" },
  { text: "Les objectifs clarifient les actions.", author: "Anonyme" },
  { text: "Le patrimoine se construit lentement.", author: "Warren Buffett" },
  { text: "La constance réduit l'incertitude.", author: "Anonyme" },
  { text: "Le capital exige de la protection.", author: "Benjamin Graham" },
  { text: "Les actifs soutiennent la liberté.", author: "Robert Kiyosaki" },
  { text: "La discipline favorise l'abondance.", author: "Anonyme" },
  { text: "Les efforts répétés créent la valeur.", author: "Anonyme" },
  { text: "Le temps récompense la rigueur.", author: "Anonyme" },
  { text: "La prudence renforce les finances.", author: "Benjamin Graham" },
  { text: "Les bonnes décisions s'accumulent.", author: "Anonyme" },
  { text: "Le savoir protège le patrimoine.", author: "Charlie Munger" },
  { text: "La cohérence développe le capital.", author: "Anonyme" },
  { text: "Les habitudes créent la stabilité.", author: "James Clear" },
  { text: "La discipline construit la richesse.", author: "Warren Buffett" },
  { text: "Épargner, c'est se payer d'abord.", author: "George S. Clason" },
  { text: "Le budget révèle les vraies priorités.", author: "Anonyme" },
  { text: "Investis dans ce que tu comprends.", author: "Peter Lynch" },
  { text: "Ne perds jamais d'argent.", author: "Warren Buffett" },
  { text: "Les frais rongent les rendements.", author: "Jack Bogle" },
  { text: "Diversifier protège de l'ignorance.", author: "Warren Buffett" },
  { text: "Le temps bat le timing.", author: "Peter Lynch" },
  { text: "Vis en dessous de tes moyens.", author: "Anonyme" },
  { text: "La dette vole ton avenir.", author: "Anonyme" },
  { text: "Achète la valeur, pas le prix.", author: "Charlie Munger" },
  { text: "Les crises sont des soldes.", author: "Anonyme" },
  { text: "Automatise ton épargne.", author: "Anonyme" },
  { text: "Un plan vaut mieux qu'une intuition.", author: "Anonyme" },
  { text: "Le cash-flow crée la liberté.", author: "Robert Kiyosaki" },
  { text: "La modération préserve la fortune.", author: "Anonyme" },
  { text: "Chaque dépense a un coût caché.", author: "Anonyme" },
  { text: "L'inflation punit l'argent dormant.", author: "Anonyme" },
  { text: "Le calme est un actif rare.", author: "Anonyme" },
  { text: "Compter, c'est déjà gagner.", author: "Anonyme" },
  { text: "La liquidité sauve en tempête.", author: "Anonyme" },
  { text: "Le savoir rapporte le plus.", author: "Benjamin Franklin" },
  { text: "Petites fuites, grands naufrages.", author: "Benjamin Franklin" },
  { text: "Investir bat spéculer.", author: "Benjamin Graham" },
  { text: "La rigueur crée l'abondance.", author: "Anonyme" },
  { text: "Sois patient, sois riche.", author: "Anonyme" },
  { text: "Un objectif clair guide l'argent.", author: "Anonyme" },
  { text: "La peur coûte plus que la crise.", author: "Anonyme" },
  { text: "Garde du cash pour les occasions.", author: "Warren Buffett" },
  { text: "La simplicité gagne à long terme.", author: "Jack Bogle" },
  { text: "Ton temps vaut plus que ton salaire.", author: "Anonyme" },
];
