// Base de citations FILAX — thématiques : investissement, économie, richesse,
// discipline financière et épargne. Citations courtes (une seule ligne).
export interface Quote {
  text: string;
  author: string;
}

export const QUOTES: Quote[] = [
  { text: "Le risque vient de ne pas savoir ce que l'on fait.", author: "Warren Buffett" },
  { text: "L'investissement doit être rationnel, pas émotionnel.", author: "Benjamin Graham" },
  { text: "L'épargne est la première marche vers la liberté financière.", author: "Anonyme" },
  { text: "La constance transforme les petites économies en fortune.", author: "Anonyme" },
  { text: "Ne dépensez jamais l'argent avant de l'avoir gagné.", author: "Thomas Jefferson" },
  { text: "Les intérêts composés sont la huitième merveille du monde.", author: "Albert Einstein" },
  { text: "La discipline financière protège contre les imprévus.", author: "Anonyme" },
  { text: "Investissez en vous-même avant d'investir dans le marché.", author: "Warren Buffett" },
  { text: "Le temps passé sur le marché bat le timing du marché.", author: "Peter Lynch" },
  { text: "L'intégrité renforce et pérennise la richesse.", author: "Anonyme" },
  { text: "Un budget dit à votre argent où aller au lieu de chercher où il est parti.", author: "John C. Maxwell" },
  { text: "Règle numéro un : ne perdez jamais d'argent.", author: "Warren Buffett" },
  { text: "La générosité prépare la croissance future.", author: "Anonyme" },
  { text: "Riche n'est pas celui qui gagne beaucoup, mais celui qui dépense peu.", author: "Proverbe Financier" },
  { text: "La patience est l'actif le plus précieux de l'investisseur.", author: "Charlie Munger" },
  { text: "Achetez quand tout le monde vend, vendez quand tout le monde achète.", author: "John Templeton" },
  { text: "L'éducation financière est le meilleur investissement.", author: "Robert Kiyosaki" },
  { text: "La maîtrise du risque précède la réalisation du profit.", author: "Anonyme" },
  { text: "L'épargne sans investissement est grignotée par l'inflation.", author: "Anonyme" },
  { text: "Le succès financier est la somme de petites décisions quotidiennes.", author: "Anonyme" },
  { text: "Ne mettez pas tous vos œufs dans le même panier.", author: "Andrew Carnegie" },
  { text: "L'argent est un bon serviteur mais un mauvais maître.", author: "Alexandre Dumas" },
  { text: "La rigueur d'aujourd'hui crée l'abondance de demain.", author: "Anonyme" },
  { text: "L'indépendance financière commence par l'élimination des dettes.", author: "Anonyme" },
  { text: "Investir, c'est renoncer à consommer aujourd'hui pour avoir plus demain.", author: "Anonyme" },
  { text: "La prudence préserve le capital sur le long terme.", author: "Ray Dalio" },
  { text: "Achetez de la valeur, pas du prix.", author: "Charlie Munger" },
  { text: "Le contrôle des dépenses est la clé de la rentabilité.", author: "Carlos Slim" },
  { text: "La connaissance des marchés réduit l'incertitude.", author: "Anonyme" },
  { text: "La confiance protège durablement la réussite.", author: "Anonyme" },
  { text: "L'épargne automatique est le secret de la constance.", author: "Anonyme" },
  { text: "Les marchés récompensent la patience et punissent l'impatience.", author: "Warren Buffett" },
  { text: "Chaque franc épargné est un ouvrier qui travaille pour vous.", author: "Anonyme" },
  { text: "L'investisseur intelligent achète pendant les crises.", author: "Benjamin Graham" },
  { text: "La gestion des émotions est plus importante que l'analyse technique.", author: "Anonyme" },
  { text: "Planifiez vos investissements et investissez selon votre plan.", author: "Anonyme" },
  { text: "La simplicité dépasse toujours la complexité en finance.", author: "Jack Bogle" },
  { text: "L'anticipation est la marque des grands investisseurs.", author: "Anonyme" },
  { text: "Gérer son budget, c'est piloter sa propre liberté.", author: "Anonyme" },
  { text: "Le rendement est la récompense de la maîtrise du risque.", author: "Anonyme" },
  { text: "N'investissez jamais dans un actif que vous ne comprenez pas.", author: "Peter Lynch" },
  { text: "La valeur est ce que vous obtenez, le prix est ce que vous payez.", author: "Warren Buffett" },
  { text: "L'épargne de précaution évite les ventes d'urgence.", author: "Anonyme" },
  { text: "La régularité bat le génie sur les marchés financiers.", author: "Anonyme" },
  { text: "Un mauvais plan vaut mieux que l'absence de plan.", author: "Anonyme" },
  { text: "La véritable richesse se mesure aux actifs qui génèrent du cash-flow.", author: "Robert Kiyosaki" },
  { text: "Diversifier, c'est se protéger contre l'ignorance.", author: "Warren Buffett" },
  { text: "La sobriété financière mène à l'indépendance durable.", author: "Anonyme" },
  { text: "Mesurez toujours la perte maximale potentielle avant le gain.", author: "Anonyme" },
  { text: "L'opportunité naît souvent là où règne le pessimisme.", author: "John Templeton" },
  { text: "L'argent suit l'attention et la bonne gestion.", author: "Anonyme" },
  { text: "L'ignorance coûte plus cher que l'éducation financière.", author: "Anonyme" },
  { text: "Payez-vous en premier avant de payer vos factures.", author: "George S. Clason" },
  { text: "La pérennité d'une fortune repose sur la modération.", author: "Anonyme" },
  { text: "Les petites dépenses inutiles coulent les grands navires.", author: "Benjamin Franklin" },
  { text: "L'investisseur de long terme ne craint pas la volatilité.", author: "Jack Bogle" },
  { text: "Le risque zéro n'existe pas, mais la gestion du risque s'apprend.", author: "Anonyme" },
  { text: "L'abondance vient à ceux qui respectent la valeur du capital.", author: "Anonyme" },
  { text: "La rentabilité naît de la discipline, pas du hasard.", author: "Anonyme" },
  { text: "Celui qui maîtrise ses désirs maîtrise ses finances.", author: "Anonyme" },
  { text: "Chaque investissement doit avoir un objectif clair et défini.", author: "Anonyme" },
  { text: "La liquidité garantit la survie lors des tempêtes économiques.", author: "Anonyme" },
  { text: "L'économie de marché récompense la création de valeur réelle.", author: "Adam Smith" },
  { text: "La sérénité financière provient de l'absence de dette toxique.", author: "Anonyme" },
  { text: "Les crises sont les soldes du monde financier.", author: "Anonyme" },
  { text: "L'esprit critique est le meilleur bouclier contre les arnaques.", author: "Anonyme" },
  { text: "Construisez des actifs, pas un style de vie éphémère.", author: "Anonyme" },
  { text: "La vision à long terme transforme la spéculation en investissement.", author: "Anonyme" },
  { text: "L'argent économisé est un dividende pour votre avenir.", author: "Anonyme" },
  { text: "Protégez votre capital initial avant de chercher le rendement.", author: "Anonyme" },
  { text: "L'automatisation de l'épargne élimine la tentation de dépenser.", author: "Anonyme" },
  { text: "L'actif le plus précieux est le temps, pas l'argent.", author: "Steve Jobs" },
  { text: "Un portefeuille équilibré résiste à toutes les saisons.", author: "Ray Dalio" },
  { text: "La lucidité financière évite les décisions sous pression.", author: "Anonyme" },
  { text: "Le profit se réalise à l'achat, pas à la vente.", author: "Proverbe Immobilier" },
  { text: "La culture du chiffre renforce la prise de décision.", author: "Anonyme" },
  { text: "L'épargne régulière surpasse les investissements occasionnels.", author: "Anonyme" },
  { text: "La véritable liberté est de ne dépendre d'aucun employeur.", author: "Anonyme" },
  { text: "La cupidité est l'ennemi numéro un de la rentabilité.", author: "Anonyme" },
  { text: "Comprendre le marché demande de la patience et de l'observation.", author: "Anonyme" },
  { text: "La capitalisation transforme le temps en richesse.", author: "Anonyme" },
  { text: "Le premier investissement doit toujours être dans votre savoir.", author: "Benjamin Franklin" },
  { text: "La rigueur budgétaire est la fondation de l'empire financier.", author: "Anonyme" },
  { text: "Remplacer l'impulsivité par l'analyse garantit le succès.", author: "Anonyme" },
  { text: "La clarté des objectifs financiers accélère leur réalisation.", author: "Anonyme" },
  { text: "Les tendances changent, mais la logique économique reste.", author: "Anonyme" },
  { text: "Conservez du cash pour saisir les opportunités rares.", author: "Warren Buffett" },
  { text: "La rentabilité est le fruit d'une stratégie éprouvée.", author: "Anonyme" },
  { text: "L'indépendance s'acquiert par le contrôle des passifs.", author: "Anonyme" },
  { text: "La stratégie bat toujours la chance sur le long terme.", author: "Anonyme" },
  { text: "Un portefeuille sain repose sur des bases fondamentales solides.", author: "Anonyme" },
  { text: "La sagesse financière consiste à vivre sous ses moyens.", author: "Anonyme" },
  { text: "La gestion du risque est l'art de survivre pour réussir.", author: "Anonyme" },
  { text: "Chaque décision financière d'aujourd'hui façonne votre futur.", author: "Anonyme" },
  { text: "L'excellence en investissement est une habitude, pas un acte.", author: "Anonyme" },
  { text: "L'épargne offre la liberté de choisir son propre chemin.", author: "Anonyme" },
  { text: "La résilience est la qualité première de l'investisseur.", author: "Anonyme" },
  { text: "Conservez une vision à long terme malgré le bruit du marché.", author: "Jack Bogle" },
  { text: "La maîtrise des coûts est le secret des portefeuilles gagnants.", author: "Anonyme" },
  { text: "La liberté financière est le pouvoir de disposer de son temps.", author: "Anonyme" },
  { text: "La discipline protège le capital.", author: "Warren Buffett" },
  { text: "L'épargne crée des options.", author: "Anonyme" },
  { text: "La patience multiplie les rendements.", author: "Warren Buffett" },
  { text: "Le risque exige la connaissance.", author: "Peter Lynch" },
  { text: "Le capital suit la confiance.", author: "Anonyme" },
  { text: "La constance construit la richesse.", author: "Anonyme" },
  { text: "Les habitudes dirigent les résultats.", author: "James Clear" },
  { text: "Chaque dépense mérite une raison.", author: "Anonyme" },
  { text: "L'investissement récompense le temps.", author: "Warren Buffett" },
  { text: "L'intégrité protège les profits.", author: "Charlie Munger" },
  { text: "Les intérêts composés favorisent les patients.", author: "Albert Einstein" },
  { text: "L'argent respecte la discipline.", author: "Anonyme" },
  { text: "Le savoir réduit le risque.", author: "Benjamin Franklin" },
  { text: "Le contrôle précède la croissance.", author: "Anonyme" },
  { text: "La prudence préserve la fortune.", author: "Benjamin Graham" },
  { text: "Les émotions coûtent cher.", author: "Warren Buffett" },
  { text: "La richesse aime la régularité.", author: "Anonyme" },
  { text: "Les décisions créent le patrimoine.", author: "Anonyme" },
  { text: "Le temps valorise les actifs.", author: "Warren Buffett" },
  { text: "L'ordre améliore les finances.", author: "Anonyme" },
  { text: "Le capital demande de la patience.", author: "Ray Dalio" },
  { text: "L'épargne prépare l'avenir.", author: "Anonyme" },
  { text: "La simplicité favorise les profits.", author: "Charlie Munger" },
  { text: "Le budget révèle les priorités.", author: "Anonyme" },
  { text: "Les objectifs orientent l'argent.", author: "Anonyme" },
  { text: "Le rendement suit la discipline.", author: "Anonyme" },
  { text: "L'attention protège les ressources.", author: "Anonyme" },
  { text: "La connaissance attire les opportunités.", author: "Peter Lynch" },
  { text: "Les chiffres racontent la vérité.", author: "Warren Buffett" },
  { text: "La maîtrise réduit les pertes.", author: "Anonyme" },
  { text: "L'action cohérente crée la richesse.", author: "Anonyme" },
  { text: "La vision guide le capital.", author: "Ray Dalio" },
  { text: "Les actifs financent la liberté.", author: "Robert Kiyosaki" },
  { text: "La prudence précède l'expansion.", author: "Benjamin Graham" },
  { text: "Le patrimoine récompense la constance.", author: "Anonyme" },
  { text: "Les bonnes habitudes enrichissent.", author: "James Clear" },
  { text: "La clarté améliore les décisions.", author: "Anonyme" },
  { text: "Le savoir accumule la valeur.", author: "Charlie Munger" },
  { text: "L'argent exige de la responsabilité.", author: "Anonyme" },
  { text: "Le progrès aime la discipline.", author: "Anonyme" },
  { text: "Les économies financent les projets.", author: "Anonyme" },
  { text: "Le capital grandit avec le temps.", author: "Warren Buffett" },
  { text: "Les résultats suivent les systèmes.", author: "James Clear" },
  { text: "La préparation réduit les erreurs.", author: "Anonyme" },
  { text: "Les profits suivent la valeur.", author: "Warren Buffett" },
  { text: "La patience protège l'investisseur.", author: "Benjamin Graham" },
  { text: "Le contrôle favorise l'abondance.", author: "Anonyme" },
  { text: "Les petites économies s'accumulent.", author: "Anonyme" },
  { text: "L'ordre crée l'efficacité.", author: "Anonyme" },
  { text: "Les actifs créent des revenus.", author: "Robert Kiyosaki" },
  { text: "La discipline renforce la liberté.", author: "Jocko Willink" },
  { text: "Les chiffres guident les décisions.", author: "Peter Drucker" },
  { text: "Le temps récompense les investisseurs.", author: "Warren Buffett" },
  { text: "L'effort cohérent produit la croissance.", author: "Anonyme" },
  { text: "La prudence protège l'avenir.", author: "Anonyme" },
  { text: "Le capital apprécie la patience.", author: "Anonyme" },
  { text: "Les choix déterminent la richesse.", author: "Anonyme" },
  { text: "La connaissance précède l'investissement.", author: "Peter Lynch" },
  { text: "Les habitudes façonnent le patrimoine.", author: "James Clear" },
  { text: "La simplicité réduit les erreurs.", author: "Charlie Munger" },
  { text: "Le budget protège les objectifs.", author: "Anonyme" },
  { text: "L'épargne réduit la dépendance.", author: "Anonyme" },
  { text: "Les actifs récompensent la vision.", author: "Robert Kiyosaki" },
  { text: "La cohérence produit les résultats.", author: "Anonyme" },
  { text: "L'argent suit la valeur créée.", author: "Warren Buffett" },
  { text: "Le savoir améliore les rendements.", author: "Peter Lynch" },
  { text: "Les ressources exigent de l'attention.", author: "Anonyme" },
  { text: "La patience évite les erreurs coûteuses.", author: "Benjamin Graham" },
  { text: "La responsabilité attire la confiance.", author: "Anonyme" },
  { text: "Les décisions façonnent l'avenir financier.", author: "Anonyme" },
  { text: "L'investissement exige de la discipline.", author: "Ray Dalio" },
  { text: "Les profits récompensent la valeur.", author: "Warren Buffett" },
  { text: "Le capital préfère la stabilité.", author: "Anonyme" },
  { text: "La vision favorise la croissance.", author: "Ray Dalio" },
  { text: "Les économies renforcent la sécurité.", author: "Anonyme" },
  { text: "La maîtrise protège les gains.", author: "Anonyme" },
  { text: "Les actifs travaillent sans repos.", author: "Robert Kiyosaki" },
  { text: "La préparation crée l'avantage.", author: "Anonyme" },
  { text: "Le temps amplifie les résultats.", author: "Warren Buffett" },
  { text: "La discipline accélère le progrès.", author: "Jocko Willink" },
  { text: "Les rendements récompensent la patience.", author: "Benjamin Graham" },
  { text: "La valeur attire le capital.", author: "Warren Buffett" },
  { text: "Les systèmes battent les impulsions.", author: "James Clear" },
  { text: "Le contrôle réduit les risques.", author: "Ray Dalio" },
  { text: "L'épargne renforce l'indépendance.", author: "Anonyme" },
  { text: "Les objectifs clarifient les actions.", author: "Anonyme" },
  { text: "Le patrimoine se construit lentement.", author: "Warren Buffett" },
  { text: "La constance réduit l'incertitude.", author: "Anonyme" },
  { text: "Les connaissances produisent des avantages.", author: "Charlie Munger" },
  { text: "Le capital exige de la protection.", author: "Benjamin Graham" },
  { text: "Les actifs soutiennent la liberté.", author: "Robert Kiyosaki" },
  { text: "La discipline favorise l'abondance.", author: "Anonyme" },
  { text: "Les efforts répétés créent la valeur.", author: "Anonyme" },
  { text: "Le temps récompense la rigueur.", author: "Anonyme" },
  { text: "La prudence renforce les finances.", author: "Benjamin Graham" },
  { text: "Les bonnes décisions s'accumulent.", author: "Anonyme" },
  { text: "Le savoir protège le patrimoine.", author: "Charlie Munger" },
  { text: "La cohérence développe le capital.", author: "Anonyme" },
  { text: "Les habitudes créent la stabilité.", author: "James Clear" },
  { text: "La discipline construit la richesse.", author: "Warren Buffett" },
];
