/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AnalyseRouteImport } from './routes/analyse'
import { Route as GroupesRouteImport } from './routes/groupes'
import { Route as InscriptionRouteImport } from './routes/inscription'
import { Route as ProfilRouteImport } from './routes/profil'
import { Route as VerificationRouteImport } from './routes/verification'
import { Route as AdminClientsRouteImport } from './routes/admin_.clients'
import { Route as AdminComptesRouteImport } from './routes/admin_.comptes'
import { Route as AdminGroupesRouteImport } from './routes/admin_.groupes'
import { Route as AdminNotificationsRouteImport } from './routes/admin_.notifications'
import { Route as GroupesIdRouteImport } from './routes/groupes_.$id'
import { Route as UserUsernameRouteImport } from './routes/user.$username'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyseRoute = AnalyseRouteImport.update({
  id: '/analyse',
  path: '/analyse',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupesRoute = GroupesRouteImport.update({
  id: '/groupes',
  path: '/groupes',
  getParentRoute: () => rootRouteImport,
} as any)
const InscriptionRoute = InscriptionRouteImport.update({
  id: '/inscription',
  path: '/inscription',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilRoute = ProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => rootRouteImport,
} as any)
const VerificationRoute = VerificationRouteImport.update({
  id: '/verification',
  path: '/verification',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminClientsRoute = AdminClientsRouteImport.update({
  id: '/admin_/clients',
  path: '/admin/clients',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminComptesRoute = AdminComptesRouteImport.update({
  id: '/admin_/comptes',
  path: '/admin/comptes',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminGroupesRoute = AdminGroupesRouteImport.update({
  id: '/admin_/groupes',
  path: '/admin/groupes',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminNotificationsRoute = AdminNotificationsRouteImport.update({
  id: '/admin_/notifications',
  path: '/admin/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupesIdRoute = GroupesIdRouteImport.update({
  id: '/groupes_/$id',
  path: '/groupes/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const UserUsernameRoute = UserUsernameRouteImport.update({
  id: '/user/$username',
  path: '/user/$username',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/analyse': typeof AnalyseRoute
  '/groupes': typeof GroupesRoute
  '/inscription': typeof InscriptionRoute
  '/profil': typeof ProfilRoute
  '/verification': typeof VerificationRoute
  '/admin/clients': typeof AdminClientsRoute
  '/admin/comptes': typeof AdminComptesRoute
  '/admin/groupes': typeof AdminGroupesRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/groupes/$id': typeof GroupesIdRoute
  '/user/$username': typeof UserUsernameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/analyse': typeof AnalyseRoute
  '/groupes': typeof GroupesRoute
  '/inscription': typeof InscriptionRoute
  '/profil': typeof ProfilRoute
  '/verification': typeof VerificationRoute
  '/admin/clients': typeof AdminClientsRoute
  '/admin/comptes': typeof AdminComptesRoute
  '/admin/groupes': typeof AdminGroupesRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/groupes/$id': typeof GroupesIdRoute
  '/user/$username': typeof UserUsernameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/analyse': typeof AnalyseRoute
  '/groupes': typeof GroupesRoute
  '/inscription': typeof InscriptionRoute
  '/profil': typeof ProfilRoute
  '/verification': typeof VerificationRoute
  '/admin_/clients': typeof AdminClientsRoute
  '/admin_/comptes': typeof AdminComptesRoute
  '/admin_/groupes': typeof AdminGroupesRoute
  '/admin_/notifications': typeof AdminNotificationsRoute
  '/groupes_/$id': typeof GroupesIdRoute
  '/user/$username': typeof UserUsernameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/analyse'
    | '/groupes'
    | '/inscription'
    | '/profil'
    | '/verification'
    | '/admin/clients'
    | '/admin/comptes'
    | '/admin/groupes'
    | '/admin/notifications'
    | '/groupes/$id'
    | '/user/$username'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/analyse'
    | '/groupes'
    | '/inscription'
    | '/profil'
    | '/verification'
    | '/admin/clients'
    | '/admin/comptes'
    | '/admin/groupes'
    | '/admin/notifications'
    | '/groupes/$id'
    | '/user/$username'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/analyse'
    | '/groupes'
    | '/inscription'
    | '/profil'
    | '/verification'
    | '/admin_/clients'
    | '/admin_/comptes'
    | '/admin_/groupes'
    | '/admin_/notifications'
    | '/groupes_/$id'
    | '/user/$username'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AnalyseRoute: typeof AnalyseRoute
  GroupesRoute: typeof GroupesRoute
  InscriptionRoute: typeof InscriptionRoute
  ProfilRoute: typeof ProfilRoute
  VerificationRoute: typeof VerificationRoute
  AdminClientsRoute: typeof AdminClientsRoute
  AdminComptesRoute: typeof AdminComptesRoute
  AdminGroupesRoute: typeof AdminGroupesRoute
  AdminNotificationsRoute: typeof AdminNotificationsRoute
  GroupesIdRoute: typeof GroupesIdRoute
  UserUsernameRoute: typeof UserUsernameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analyse': {
      id: '/analyse'
      path: '/analyse'
      fullPath: '/analyse'
      preLoaderRoute: typeof AnalyseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groupes': {
      id: '/groupes'
      path: '/groupes'
      fullPath: '/groupes'
      preLoaderRoute: typeof GroupesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inscription': {
      id: '/inscription'
      path: '/inscription'
      fullPath: '/inscription'
      preLoaderRoute: typeof InscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profil': {
      id: '/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof ProfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verification': {
      id: '/verification'
      path: '/verification'
      fullPath: '/verification'
      preLoaderRoute: typeof VerificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/clients': {
      id: '/admin_/clients'
      path: '/admin/clients'
      fullPath: '/admin/clients'
      preLoaderRoute: typeof AdminClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/comptes': {
      id: '/admin_/comptes'
      path: '/admin/comptes'
      fullPath: '/admin/comptes'
      preLoaderRoute: typeof AdminComptesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/groupes': {
      id: '/admin_/groupes'
      path: '/admin/groupes'
      fullPath: '/admin/groupes'
      preLoaderRoute: typeof AdminGroupesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/notifications': {
      id: '/admin_/notifications'
      path: '/admin/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AdminNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groupes_/$id': {
      id: '/groupes_/$id'
      path: '/groupes/$id'
      fullPath: '/groupes/$id'
      preLoaderRoute: typeof GroupesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/$username': {
      id: '/user/$username'
      path: '/user/$username'
      fullPath: '/user/$username'
      preLoaderRoute: typeof UserUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AnalyseRoute: AnalyseRoute,
  GroupesRoute: GroupesRoute,
  InscriptionRoute: InscriptionRoute,
  ProfilRoute: ProfilRoute,
  VerificationRoute: VerificationRoute,
  AdminClientsRoute: AdminClientsRoute,
  AdminComptesRoute: AdminComptesRoute,
  AdminGroupesRoute: AdminGroupesRoute,
  AdminNotificationsRoute: AdminNotificationsRoute,
  GroupesIdRoute: GroupesIdRoute,
  UserUsernameRoute: UserUsernameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
