/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as InscriptionRouteImport } from './routes/inscription'
import { Route as EconomieRouteImport } from './routes/economie'
import { Route as DisciplineRouteImport } from './routes/discipline'
import { Route as AssuranceRouteImport } from './routes/assurance'
import { Route as IndexRouteImport } from './routes/index'

const InscriptionRoute = InscriptionRouteImport.update({
  id: '/inscription',
  path: '/inscription',
  getParentRoute: () => rootRouteImport,
} as any)
const EconomieRoute = EconomieRouteImport.update({
  id: '/economie',
  path: '/economie',
  getParentRoute: () => rootRouteImport,
} as any)
const DisciplineRoute = DisciplineRouteImport.update({
  id: '/discipline',
  path: '/discipline',
  getParentRoute: () => rootRouteImport,
} as any)
const AssuranceRoute = AssuranceRouteImport.update({
  id: '/assurance',
  path: '/assurance',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assurance': typeof AssuranceRoute
  '/discipline': typeof DisciplineRoute
  '/economie': typeof EconomieRoute
  '/inscription': typeof InscriptionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assurance': typeof AssuranceRoute
  '/discipline': typeof DisciplineRoute
  '/economie': typeof EconomieRoute
  '/inscription': typeof InscriptionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assurance': typeof AssuranceRoute
  '/discipline': typeof DisciplineRoute
  '/economie': typeof EconomieRoute
  '/inscription': typeof InscriptionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/assurance' | '/discipline' | '/economie' | '/inscription'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/assurance' | '/discipline' | '/economie' | '/inscription'
  id:
    | '__root__'
    | '/'
    | '/assurance'
    | '/discipline'
    | '/economie'
    | '/inscription'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssuranceRoute: typeof AssuranceRoute
  DisciplineRoute: typeof DisciplineRoute
  EconomieRoute: typeof EconomieRoute
  InscriptionRoute: typeof InscriptionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/inscription': {
      id: '/inscription'
      path: '/inscription'
      fullPath: '/inscription'
      preLoaderRoute: typeof InscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/economie': {
      id: '/economie'
      path: '/economie'
      fullPath: '/economie'
      preLoaderRoute: typeof EconomieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discipline': {
      id: '/discipline'
      path: '/discipline'
      fullPath: '/discipline'
      preLoaderRoute: typeof DisciplineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assurance': {
      id: '/assurance'
      path: '/assurance'
      fullPath: '/assurance'
      preLoaderRoute: typeof AssuranceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssuranceRoute: AssuranceRoute,
  DisciplineRoute: DisciplineRoute,
  EconomieRoute: EconomieRoute,
  InscriptionRoute: InscriptionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
